# Generated by Django 5.2.7 on 2025-10-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('year', models.CharField()),
                ('genre', models.CharField()),
                ('style', models.CharField()),
                ('cover_image', models.CharField()),
                ('master_id', models.IntegerField()),
            ],
        ),
    ]
