# Generated by Django 5.2.7 on 2025-10-23 05:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='style',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
    ]
