# Generated by Django 5.2.7 on 2025-10-23 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_album_genre_alter_album_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='style',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.CharField(blank=True),
        ),
    ]
