# Generated by Django 5.2.7 on 2025-10-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_album_slug_alter_album_cover_image_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
