# Generated by Django 5.2.7 on 2025-10-23 08:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='master_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='style',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
